<?php

namespace Tests;

use App\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        // Potrei spegnerle a livello globale lanciando il metodo $this->withoutExceptionHandling() qui
        // e dove invece voglio che il framework gestisca le eccezzioni utilizzo il metodo $this->withExceptionHandling()

        $this->withoutExceptionHandling(); // Se voglio disabilitare la gestione delle eccezzioni da parte del framework
        //$this->withExceptionHandling(); // Se voglio abilitare la gestione delle eccezzioni da parte del framework

        // ad esempio per l'autenticazione, se tento di accedere a qualcosa protetto da auth e non solo loggato
            // se HO abilitato la gestione delle eccezzioni non ricevo alcun errore, il sistema non lancia eccezzioni e vengo rediretto alla pagina di login
            // quindi devo controllare se effettivamente vengo rediretto in home

            // se NON HO abilitato la gestione delle eccezzioni, il sistema lancia eccezzione di utente non autenticato
            // quindi devo controllare se ricevo questo tipo di eccezzione
    }

    // Helper custom per creazione dell'utente
    protected function signIn($user = null)
    {
        $user = $user ?: create(User::class);

        $this->actingAs($user);

        return $this;
    }
}
