<?php

namespace Tests;

use App\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        // Potrei spegnerle a livello globale lanciando il metodo $this->withoutExceptionHandling() qui
        // e dove invece voglio che il framework gestisca le eccezzioni utilizzo il metodo $this->withExceptionHandling()

        $this->withoutExceptionHandling(); // Se voglio disabilitare la gestione delle eccezzioni da parte del framework
        //$this->withExceptionHandling(); // Se voglio abilitare la gestione delle eccezzioni da parte del framework
    }

    // Helper custom per creazione dell'utente
    protected function signIn($user = null)
    {
        $user = $user ?: create(User::class);

        $this->actingAs($user);

        return $this;
    }
}
